### ISSUE TITLE
Connection parameter breaks SAML login

### ISSUE THREAD

**Issue by zamd** [auth0-extensions/auth0-sso-dashboard-extension#11]
When the `connection` parameter is specified in the `New Application` form, it incorrectly gets encoded as `&` to login url instead of `?` which fails the SAML login

Broken URL: `https://{domain}.auth0.com/samlp/HbOLz0nYYKCwR0sjBf2MoUo2w5jaAGnI&connection=db`

Working URL: `https://internalserver.auth0.com/samlp/HbOLz0nYYKCwR0sjBf2MoUo2w5jaAGnI?connection=db`

**Comment by pushpabrol** [comment]
The connection parameter is being added with an & as the separator between url path and the query parameters but it should be using a ?.  The SSO is not demonstrable because of this issue

**Comment by andyklaiber** [comment]
This is definitely still broken.  I just worked around it using the custom url.
